### ISSUE TITLE
Add constants for magic numbers

### ISSUE THREAD

**Issue by tjohnson-scottlogic** [ECMWFCode4Earth/vAirify#183]
There are a few instances of numbers used in our code where it is not obvious how these numbers have been determined.  For example 
forecast_dao.py includes the number 41:

class CamsRequestDetails:

    def __init__(
        self, base_forecast_datetime: datetime, no_of_forecast_times: int = 41
    ):
        self.base_forecast_datetime = base_forecast_datetime
        self.no_of_forecast_times = no_of_forecast_times

This ticket is for reviewing the codebase for numbers like these and adding constants for them to improve the readability / maintainability of the code, with additional comments if needed.

Acceptance Criteria

- Any "magic" numbers are defined as constants
- This only covers the UI and backend code, doesn't cover tests
- Regression should have been run (no functional change in this ticket)
- 
Test Checklist:
- [x] Test Analysis & discussion with developer
- [ ] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- No functional change, just need to run regression tests and ensure they pass

**Comment by mwalker-scottlogic** [comment]
Backend tests - PASSED ✅ 

![Image](https://github.com/user-attachments/assets/21689893-0936-41f8-b804-99b370de3aa4)

Frontend tests - 33 Failed, all to do with snapshots

![Image](https://github.com/user-attachments/assets/ab2e590e-e7f3-4a8c-9798-7fee2efa7796)

AQI graph snapshot is failing because the line has changed

![Image](https://github.com/user-attachments/assets/0ee991c3-efa3-4782-bdd9-b008712d9234)

Pollutant graphs are failing as expecting dimensions 600 x 400 but getting 601 x 400

![Image](https://github.com/user-attachments/assets/ba27ad74-48e9-4efb-9b13-678d910aaba6)

No2 is correct dimensions but 192 pixels (ratio 0.01 of all image pixels) are different.
 
![Image](https://github.com/user-attachments/assets/6d2b2004-8b60-4268-baa4-f249639624b3)


note: webkit tests are expecting and getting a different size: Expected an image 1200px by 800px, received 1202px by 800px

**Comment by mwalker-scottlogic** [comment]
Regression Tests Passed ✅ 

- Backend system tests

![Image](https://github.com/user-attachments/assets/3989ec5a-3dee-46cd-9c35-b5f5e2d8a842)

Frontend system tests

![Image](https://github.com/user-attachments/assets/2d2b3065-6430-4c8b-b495-3dd67166e5e2)
