### ISSUE TITLE
[UI] As a user I want the ability to view the CityPage UI on screen sizes smaller than 1920x1080

### ISSUE THREAD

**Issue by mnyamunda-scottlogic** [ECMWFCode4Earth/vAirify#230]
Currently when the screen sizing is changed. The leftmost graphs become hidden and cannot be scrolled to. 
Elements are only fully displayed at 1920x1080

### Acceptance criteria
- Despite screen size, user should be able to scroll each element into view
- Include some snapshot testing around some different screen sizes

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by Ben-EJ** [comment]
## Test Analysis

- Verify that the leftmost graphs become hidden and can be scrolled to, even if the screen has been shrunk.

**Comment by Ben-EJ** [comment]
Charter: https://github.com/ECMWFCode4Earth/vAirify/wiki/Charter-19-As-a-user-I-want-the-ability-to-view-the-CityPage-UI-on-screen-sizes-smaller-than-1920x1080

**Comment by mwalker-scottlogic** [comment]
Backend tests - PASSED ✅ 

![Image](https://github.com/user-attachments/assets/21689893-0936-41f8-b804-99b370de3aa4)

Frontend tests - 33 Failed, all to do with snapshots

![Image](https://github.com/user-attachments/assets/ab2e590e-e7f3-4a8c-9798-7fee2efa7796)

AQI graph snapshot is failing because the line has changed

![Image](https://github.com/user-attachments/assets/0ee991c3-efa3-4782-bdd9-b008712d9234)

Pollutant graphs are failing as expecting dimensions 600 x 400 but getting 601 x 400

![Image](https://github.com/user-attachments/assets/ba27ad74-48e9-4efb-9b13-678d910aaba6)

No2 is correct dimensions but 192 pixels (ratio 0.01 of all image pixels) are different.
 
![Image](https://github.com/user-attachments/assets/6d2b2004-8b60-4268-baa4-f249639624b3)


note: webkit tests are expecting and getting a different size: Expected an image 1200px by 800px, received 1202px by 800px

**Comment by mwalker-scottlogic** [comment]
Regression Tests Passed ✅ 

- Backend system tests

![Image](https://github.com/user-attachments/assets/3989ec5a-3dee-46cd-9c35-b5f5e2d8a842)

Frontend system tests

![Image](https://github.com/user-attachments/assets/2d2b3065-6430-4c8b-b495-3dd67166e5e2)

# #

[Playwright Regression 25.07.24.pdf](https://github.com/user-attachments/files/16379307/Playwright.Regression.25.07.24.pdf)

**Comment by mwalker-scottlogic** [comment]
### Regression - PASSED

- Frontend

![Image](https://github.com/user-attachments/assets/9ba190c7-0d77-4a4d-97b2-5c74c176c4f4)

[Playwright Regression 29.07.24.pdf](https://github.com/user-attachments/files/16415142/Playwright.Regression.29.07.24.pdf)

- Backend

![Image](https://github.com/user-attachments/assets/b8e591ec-c5ba-4d28-8f49-93b82a2c05ba)

**Comment by mnyamunda-scottlogic** [comment]
[celebrate]     Max Nyamunda reacted to your message:
________________________________
