### ISSUE TITLE
Style the AQI graph to look like the others on the city page

### ISSUE THREAD

**Issue by tjohnson-scottlogic** [ECMWFCode4Earth/vAirify#234]
The AQI graph is styled differently to the others, and we should update it to make it consistent in appearance.

- Update the forecast line to be black, bold and dashed as per the other graphs
- Remove the key (forecast/measured legend)
- Auto zoom onto the same date period as the others and include the zoom bar
- Style the data points as the other graphs, not a circle but a solid dot
- Make the x-axis time scale match the others
- Update snapshot testing for this graph
- Add a wiki page detailing what is covered by snapshot testing to allow us to ensure we don't regress functionality by taking a new snapshot

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
Backend tests - PASSED ✅ 

![Image](https://github.com/user-attachments/assets/21689893-0936-41f8-b804-99b370de3aa4)

Frontend tests - 33 Failed, all to do with snapshots

![Image](https://github.com/user-attachments/assets/ab2e590e-e7f3-4a8c-9798-7fee2efa7796)

AQI graph snapshot is failing because the line has changed

![Image](https://github.com/user-attachments/assets/0ee991c3-efa3-4782-bdd9-b008712d9234)

Pollutant graphs are failing as expecting dimensions 600 x 400 but getting 601 x 400

![Image](https://github.com/user-attachments/assets/ba27ad74-48e9-4efb-9b13-678d910aaba6)

No2 is correct dimensions but 192 pixels (ratio 0.01 of all image pixels) are different.
 
![Image](https://github.com/user-attachments/assets/6d2b2004-8b60-4268-baa4-f249639624b3)


note: webkit tests are expecting and getting a different size: Expected an image 1200px by 800px, received 1202px by 800px

**Comment by rstrange-scottlogic** [comment]
**Test Analysis**

- The forecast line is black, bold and dashed as per the other graphs
- Key has been removed (forecast/measured legend)
- Graph auto-zooms onto the same date period as the others and includes the zoom bar
- Data points are styled as the other graphs, not a circle but a solid dot
- X-axis time scale matches the others at various grnaularity
- Snapshots updated
- Wiki page exists for snapshots
