### ISSUE TITLE
Update PM 2.5 and PM 10 not to have a space in the UI

### ISSUE THREAD

**Issue by rstrange-scottlogic** [ECMWFCode4Earth/vAirify#237]
The UI currently displays PM 2.5 and PM 10 with a space, we want to remove the space, so that it appears PM2.5 and PM10.
Update snapshot and playwright test

Test Checklist:
- [x] Test Analysis & discussion with developer
- [ ] Write Test Cases / Charters
- [ ] Test Cases & Charters Reviewed
- [ ] Test Cases Executed
- [ ] Test Charters Executed
- [x] Regression tests executed
- [ ] Automation Tests added to project

**Comment by mnyamunda-scottlogic** [comment]
Test Analysis. 

- Verify the whitespace is removed.
  - Update snapshots 
  - Write new assertions for the Chart title e.g. Assert exact text within that locator.

**Comment by mwalker-scottlogic** [comment]
Backend tests - PASSED ✅ 

![Image](https://github.com/user-attachments/assets/21689893-0936-41f8-b804-99b370de3aa4)

Frontend tests - 33 Failed, all to do with snapshots

![Image](https://github.com/user-attachments/assets/ab2e590e-e7f3-4a8c-9798-7fee2efa7796)

AQI graph snapshot is failing because the line has changed

![Image](https://github.com/user-attachments/assets/0ee991c3-efa3-4782-bdd9-b008712d9234)

Pollutant graphs are failing as expecting dimensions 600 x 400 but getting 601 x 400

![Image](https://github.com/user-attachments/assets/ba27ad74-48e9-4efb-9b13-678d910aaba6)

No2 is correct dimensions but 192 pixels (ratio 0.01 of all image pixels) are different.
 
![Image](https://github.com/user-attachments/assets/6d2b2004-8b60-4268-baa4-f249639624b3)


note: webkit tests are expecting and getting a different size: Expected an image 1200px by 800px, received 1202px by 800px

**Comment by mwalker-scottlogic** [comment]
Regression Tests Passed ✅ 

- Backend system tests

![Image](https://github.com/user-attachments/assets/3989ec5a-3dee-46cd-9c35-b5f5e2d8a842)

Frontend system tests

![Image](https://github.com/user-attachments/assets/2d2b3065-6430-4c8b-b495-3dd67166e5e2)
