### ISSUE TITLE
[Failing Test] - `forecast_calibration_test.py` - Beijing o3

### ISSUE THREAD

**Issue by mwalker-scottlogic** [ECMWFCode4Earth/vAirify#340]
Running the backend regression tests yesterday and this morning, I picked up  a test failure in `forecast_calibration_test.py`.

The test compares the forecast data on the ftp server for a specific base time to the forecast data stored in the database for the same base time and checks there isn't a divergence of more than 3%.

The test failure is specifically for Beijing, and for the pollutant o3

![Image](https://github.com/user-attachments/assets/4c18ca10-ac69-414e-9d13-e7766de94f98)

**Comment by Ben-EJ** [comment]
![Image](https://github.com/user-attachments/assets/79adc654-3924-41f9-86ed-3165582b35fa)
![Image](https://github.com/user-attachments/assets/0d81fd07-0bf2-4499-adc1-bbc7c143228a)
It would seem that the number from the FTP has been rounded and because the numbers are so small this is causing a massive differential causing the error.

**Comment by mwalker-scottlogic** [comment]
PR raised to amend test to round to 3dp
