### ISSUE TITLE
[UI] As a system user I want to change the forecast base date so I can perform analysis on multiple forecasts

### ISSUE THREAD

**Issue by amehta-scottlogic** [ECMWFCode4Earth/vAirify#74]
## Acceptance Criteria

This applies to all screens.

- A date picker exists in the header to select forecast_base_time.
- When selected, API should be re-queried to fetch data for this forecast_base_time
- Dates can only be in the past and must be either midday or midnight
- Add a label next to the date picker showing the date range
- Remove the base date text from the top of the summary page and the forecast range
-  e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
  - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

Testing is through playwright with mocked API's
This will affect the summary and city pages
No automated e2e tests as part of this ticket

Test Checklist:
- [x] Test Analysis & discussion with developer
- [x] Write Test Cases / Charters
- [x] Test Cases & Charters Reviewed
- [x] Test Cases Executed
- [x] Test Charters Executed
- [x] Regression tests executed
- [x] Automation Tests added to project

**Comment by mwalker-scottlogic** [comment]
### Test Analysis

- Verify date picker is in the header
  - city view
  - summary view
  - Automation tests in `banner.spec.ts` checking it exists
- Verify date picker triggers the correct API calls
  - Automation test to check the forecast request on page load vs after selecting date
  - Assert the forecast base time changes in the request
  - Assert the label next to the date picker updates correctly
- Verify dates can't be in the future
- Verify dates can only be 12 or 00
  - what happens if system time is set to 11 and you query 12 for today?
- Remove test that asserts on forecast base time text 
- Verify the UI is updated with new mocked data when changing the base date
  - mock the response from the API for page load
  - change the date
  - mock the response of the API with the different date
  - Summary page - check the table updates correctly
  - City page - snapshots should change

**Comment by mnyamunda-scottlogic** [comment]
- setBaseTime POM code written for citypage , can share and duplicate for summary.
- Existing `setBaseTime` method is takes in a string, so we can actually force a future date and time to see what happens.

Otherwise, no further points. Looks good 💯

**Comment by mwalker-scottlogic** [comment]
Regression Tests Passed ✅ 

- Backend system tests

![Image](https://github.com/user-attachments/assets/3989ec5a-3dee-46cd-9c35-b5f5e2d8a842)

Frontend system tests

![Image](https://github.com/user-attachments/assets/2d2b3065-6430-4c8b-b495-3dd67166e5e2)

# #

[Playwright Regression 25.07.24.pdf](https://github.com/user-attachments/files/16379307/Playwright.Regression.25.07.24.pdf)

**Comment by mwalker-scottlogic** [comment]
### Finding - Can send a future date via keys
Relevant AC:

- 'Dates can only be in the past and must be either midday or midnight'

Steps to reproduce:

- Click in the textbox next to the date picker
- enter a future date
- check the network requests

Expected:

- Unable to provide a future data

Actual:

- API requests the data
- Displays empty graphs & tables


![Image](https://github.com/user-attachments/assets/f7099e24-7b42-4204-8191-1d731e241828)


![Image](https://github.com/user-attachments/assets/e057399a-53f5-4bf8-a115-8e71ec66e37f)

**Comment by mwalker-scottlogic** [comment]
failing regression tests on merge

**Comment by mwalker-scottlogic** [comment]
Regression -  31/07 PASSED ✅ 

- Frontend:

![Image](https://github.com/user-attachments/assets/a1cea07a-83c0-4cbc-830a-d8d4d8316f6a)

[Playwright Regression 31.07.24.pdf](https://github.com/user-attachments/files/16444382/Playwright.Regression.31.07.24.pdf)

- Backend:

![Image](https://github.com/user-attachments/assets/e6b672e6-fdca-48c1-ac84-4e9428a59330)
